### ISSUE TITLE
Failed to load the atom-psql package

### ISSUE THREAD

**Issue by ihabhussein** [maisk/atom-psql#3]
[Enter steps to reproduce:]

1. Upgrade atom-sql to 0.22.0
2. Relaunch atom

**Atom**: 1.23.1 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.13.2
**Thrown From**: [atom-psql](https://github.com/maisk/atom-psql) package 0.22.0

### Stack Trace

Failed to load the atom-psql package

```
At variable @tab-text-color-editor is undefined in /Users/ihab/.atom/packages/atom-psql/styles/terminal.less:9:9

LessError: variable @tab-text-color-editor is undefined
  at /packages/atom-psql/styles/terminal.less:9:9
```

### Commands

```
```

### Non-Core Packages

```
atom-psql 0.22.0 
editorconfig 2.2.2 
git-log 0.4.1 
language-diff 0.7.0 
language-gettext 0.6.1 
language-ini 1.19.0 
language-latex 1.1.1 
language-nginx 0.8.0 
language-perl6 1.16.0 
language-pgsql 0.2.3 
language-restructuredtext 1.1.0 
minimap 4.29.7 
minimap-git-diff 4.3.1 
pipe 0.4.0 
platformio-ide-terminal 2.7.0 
pretty-json 1.6.4 
rst-preview 1.3.1 
tree-view-git-branch 0.1.2 
xml-formatter 0.11.0 
```

**Comment by maisk** [comment]
i dont have mac to test it but i think that i fix this.
if you can try the new version.
thank you for the report.

**Comment by ihabhussein** [comment]
Version 0.25.0 solves the problem and works perfectly.
Thank you for a very useful package.
